#ifndef OPENCVTOQML_GLOBAL_H
#define OPENCVTOQML_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(OPENCVTOQML_LIBRARY)
#  define OPENCVTOQMLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENCVTOQMLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENCVTOQML_GLOBAL_H

